{
 "title": "GitHub",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "owner",
    "label": "Owner",
    "query": {
     "query": "label_values(github_stargazers_total, owner)"
    }
   },
   {
    "name": "repository",
    "label": "Repository",
    "query": {
     "query": "label_values(github_stargazers_total, repository)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Stargazers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(github_stargazers_total)" }
   ]
  },
  {
   "title": "Total Forks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(github_forks_total)" }
   ]
  },
  {
   "title": "Total Additions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "(+)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(github_additions_total)" }
   ]
  },
  {
   "title": "Total Deletions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "(-)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(github_deletions_total)" }
   ]
  },
  {
   "title": "Total Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(github_size_total)" }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Fork Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "github_forks_total{owner=~\"$owner\", repository=~\"$repository\"}",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Stargazers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "github_stargazers_total{owner=~\"$owner\", repository=~\"$repository\"}",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Additions / Deletions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "github_additions_total{owner=~\"$owner\", repository=~\"$repository\"}",
     "legendFormat": "Additions: {{repository}}"
    },
    {
     "expr": "-github_deletions_total{owner=~\"$owner\", repository=~\"$repository\"}",
     "legendFormat": "Deletions: {{repository}}"
    }
   ]
  },
  {
   "title": "Open Issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "github_open_issues_total{owner=~\"$owner\", repository=~\"$repository\"}",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "github_size_total{owner=~\"$owner\", repository=~\"$repository\"}",
     "legendFormat": "{{repository}}"
    }
   ]
  }
 ]
}