version: '3.7'
services:
  gh-prom-exporter:
    image: ghcr.io/skuzzle/gh-prom-exporter/gh-prom-exporter:${VERSION:?VERSION property not defined or empty}
#    healthcheck:
#      test: ["CMD", "curl" , "-f", "http://localhost:9000/actuator/health"]
#      interval: 20s
#      timeout: 10s
#      retries: 5
    networks:
    - traefik_proxy
    - monitoring
    environment:
      # GH Issue #8: https://github.com/skuzzle/gh-prom-exporter/issues/8
      # mitigate false positives during abuse detection
      WEB_ABUSE_LIMIT: '20'
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.http.routers.gh-prom-exporter.tls: 'true'
        traefik.http.routers.gh-prom-exporter.tls.certresolver: le
        traefik.http.routers.gh-prom-exporter.rule: Host(`gh.skuzzle.de`)
        traefik.http.routers.gh-prom-exporter.entrypoints: https
        traefik.http.services.gh-prom-exporter.loadbalancer.server.port: 8080
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

networks:
  traefik_proxy:
    external: true
    name: traefik_proxy
  monitoring:
    external: true
    name: monitoring
